### ISSUE TITLE
Gives error

### ISSUE THREAD

**Issue by rahulkumaran** [mrsaicharan1/Nebula#2]
https://github.com/mrsaicharan1/Nebula/blob/80ac85c49678867b69f439a443fd571a0cf28804/blockchain.py#L59

**Comment by rahulkumaran** [comment]
![screenshot from 2018-06-10 22-50-51](https://user-images.githubusercontent.com/26206171/41204338-c6bf0874-6d00-11e8-9284-1a4356fa1130.png)

**Comment by mrsaicharan1** [comment]
I've faced the problem myself many times. But somehow figured it out. Will see in a moment!

**Comment by rahulkumaran** [comment]
Still gives error xD

**Comment by mrsaicharan1** [comment]
Documentation under process xD
